#!/usr/bin/env python3
from os import environ, makedirs
import re

target = environ.get('TARGET')
if not target:
  print('::error ::TARGET is required but missing')
  exit(1)

release_tag = environ.get('RELEASE_TAG')
if not release_tag:
  print('::error ::RELEASE_TAG is required but missing')
  exit(1)

checksum = None
word_splitter = re.compile(r'\s+')
for line in open('checksums/sha1sum.txt').readlines():
  line = line.strip()
  if line.endswith(target):
    checksum, _ = word_splitter.split(line)

maintainer = '# Maintainer: oxod <me@oxod.nl>\n'
license_url = 'https://raw.githubusercontent.com/oxodx/cppfetch/master/LICENSE.md'

opening = maintainer + '\n# This file is automatically generated. Do not edit.\n'

print('Generating PKGBUILD for cppfetch...')
makedirs('./pkgbuild/cppfetch', exist_ok=True)
with open('./pkgbuild/cppfetch/PKGBUILD', 'w') as pkgbuild:
  content = opening + '\n'
  content += 'pkgname=cppfetch\n'
  content += f'pkgver={release_tag}\n'
  source_url = f'https://github.com/oxodx/cppfetch/archive/{release_tag}.tar.gz'
  content += f'source=(cppfetch-{release_tag}.tar.gz::{source_url} {license_url})\n'
  content += 'sha1sums=(SKIP SKIP)\n'
  content += open('./packaging/aur/PKGBUILD').read() + '\n'
  pkgbuild.write(content)
