#!/usr/bin/env python3
from os import environ, makedirs

release_tag = environ.get('RELEASE_TAG')
if not release_tag:
  print('::error ::RELEASE_TAG is required but missing')
  exit(1)

maintainer = '# Maintainer: oxod <me@oxod.nl>\n'
license_url = 'https://raw.githubusercontent.com/oxodx/cppfetch/master/LICENSE.md'

opening = maintainer + '\n# This file is automatically generated. Do not edit.\n'

print('Generating PKGBUILD for cppfetch...')
makedirs('./packaging/aur', exist_ok=True)
with open('./packaging/aur/PKGBUILD', 'w') as pkgbuild:
  content = opening + '\n'
  content += 'pkgname=cppfetch\n'
  content += f'pkgver={release_tag}\n'
  source_url = f'https://github.com/oxodx/cppfetch/archive/{release_tag}.tar.gz'
  content += f'source=(cppfetch-{release_tag}.tar.gz::{source_url} {license_url})\n'
  content += 'sha1sums=(SKIP SKIP)\n'
  content += open('./packaging/aur/PKGBUILD').read() + '\n'
  pkgbuild.write(content)
