#pragma once
#include <string>
#include <vector>

std::string getUsername();
std::string getHostname();
std::string getOS();
std::string getKernel();
std::string getCPU();
std::vector<std::string> getGPU();
std::string getRAM();
std::string getSwap();
std::string getRootStorage();
std::string getUptime();
std::string getShell();
std::string getTerminal();
std::string getDE();
std::string getDisplayServer();
std::string getPackages();
std::string makeSeparator();
std::string getDisplay();
std::string getLocalIP();
